# Site settings
author: TaeVon J Lewis
title: Why Software Engineering is Right For Me
header-img: img/home-bg.png
email: lewistpro@gmail.com
copyright_name: TaeVon J Lewis
description: > # this means to ignore newlines until "baseurl:"
  Lessons Learned
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lewist13

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
